services:
  bokeh-app:
    image: epinux/ncmet:latest
    hostname: bokeh-app
    volumes:
      - ./bokeh/main.py:/app/main.py
      - ./bokeh/entrypoint.sh:/entrypoint.sh  
    entrypoint: ["bokeh", "serve", "/app/", "--address", "0.0.0.0", "--port", "5006", "--allow-websocket-origin=*"]  
    # command: ["bokeh", "serve", "--allow-websocket-origin=*", "--port=5006", "/app/main.py"]

